apiVersion: apps/v1
kind: Deployment
metadata:
  name: wekan-retriever
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wekan-retriever
  template:
    metadata:
      labels:
        app: wekan-retriever
        version: v1
    spec:
      containers:
      - name: wekan-retriever
        image: gunter04/wekanretriever:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        volumeMounts:
        - mountPath: /code/dbdata
          name: dbdata  
      volumes:
      - name: dbdata
        persistentVolumeClaim: 
          claimName: wekan-data-pvc
          readOnly: false # Read and write
